//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travely.Client.Resources.UIResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PageNameResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageNameResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Travely.Client.Resources.UIResources.PageNameResources", typeof(PageNameResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRAVELY.
        /// </summary>
        internal static string DashboardPageName {
            get {
                return ResourceManager.GetString("DashboardPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Trip.
        /// </summary>
        internal static string EditTripPageName {
            get {
                return ResourceManager.GetString("EditTripPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itinerary.
        /// </summary>
        internal static string ItineraryPageName {
            get {
                return ResourceManager.GetString("ItineraryPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Map.
        /// </summary>
        internal static string MapPageName {
            get {
                return ResourceManager.GetString("MapPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan a trip.
        /// </summary>
        internal static string PlanTripPageName {
            get {
                return ResourceManager.GetString("PlanTripPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string ProfilePageName {
            get {
                return ResourceManager.GetString("ProfilePageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack for your trip.
        /// </summary>
        internal static string TripPackingPageName {
            get {
                return ResourceManager.GetString("TripPackingPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Trips.
        /// </summary>
        internal static string TripPageName {
            get {
                return ResourceManager.GetString("TripPageName", resourceCulture);
            }
        }
    }
}
