//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travely.Client.Resources.UIResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Travely.Client.Resources.UIResources.ValidationResources", typeof(ValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing item added successfully..
        /// </summary>
        internal static string AddPackingItemSuccess {
            get {
                return ResourceManager.GetString("AddPackingItemSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip added successfully..
        /// </summary>
        internal static string AddTripSuccess {
            get {
                return ResourceManager.GetString("AddTripSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save this location?.
        /// </summary>
        internal static string ConfirmLocation {
            get {
                return ResourceManager.GetString("ConfirmLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm location.
        /// </summary>
        internal static string ConfirmLocationTitle {
            get {
                return ResourceManager.GetString("ConfirmLocationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight number cannot be empty..
        /// </summary>
        internal static string EmptyArrivalFlightError {
            get {
                return ResourceManager.GetString("EmptyArrivalFlightError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight number cannot be empty..
        /// </summary>
        internal static string EmptyDepartureFlightError {
            get {
                return ResourceManager.GetString("EmptyDepartureFlightError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item title cannot be empty..
        /// </summary>
        internal static string EmptyItemError {
            get {
                return ResourceManager.GetString("EmptyItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note cannot be empty..
        /// </summary>
        internal static string EmptyNoteError {
            get {
                return ResourceManager.GetString("EmptyNoteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title cannot be empty..
        /// </summary>
        internal static string EmptyTitleError {
            get {
                return ResourceManager.GetString("EmptyTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An item with the same title already exists..
        /// </summary>
        internal static string ExistItemError {
            get {
                return ResourceManager.GetString("ExistItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight number must be exactly 8 digits..
        /// </summary>
        internal static string InvalidArrivalFlightError {
            get {
                return ResourceManager.GetString("InvalidArrivalFlightError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight number must be exactly 8 digits..
        /// </summary>
        internal static string InvalidDepartureFlightError {
            get {
                return ResourceManager.GetString("InvalidDepartureFlightError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination cannot be empty and must contain only letters..
        /// </summary>
        internal static string InvalidDestinationError {
            get {
                return ResourceManager.GetString("InvalidDestinationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date is not valid..
        /// </summary>
        internal static string InvalidEndDate {
            get {
                return ResourceManager.GetString("InvalidEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item title can only contain letters, digits and spaces..
        /// </summary>
        internal static string InvalidItemError {
            get {
                return ResourceManager.GetString("InvalidItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note must contain only letters, numbers, and spaces..
        /// </summary>
        internal static string InvalidNoteError {
            get {
                return ResourceManager.GetString("InvalidNoteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date is not valid..
        /// </summary>
        internal static string InvalidStartDate {
            get {
                return ResourceManager.GetString("InvalidStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title must contain only letters, numbers, and spaces..
        /// </summary>
        internal static string InvalidTitleError {
            get {
                return ResourceManager.GetString("InvalidTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
