//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travely.BusinessLogic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class APICallResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal APICallResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Travely.BusinessLogic.Resources.APICallResources", typeof(APICallResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.first.org/data/v1/countries?region=.
        /// </summary>
        internal static string CountriesAPI {
            get {
                return ResourceManager.GetString("CountriesAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://countriesnow.space/api/v0.1/countries/currency.
        /// </summary>
        internal static string CountryCurrencyAPI {
            get {
                return ResourceManager.GetString("CountryCurrencyAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://countriesnow.space/api/v0.1/countries/positions.
        /// </summary>
        internal static string CountryLatitudeAPI {
            get {
                return ResourceManager.GetString("CountryLatitudeAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://flagcdn.com/w320/{0}.png.
        /// </summary>
        internal static string FlagAPI {
            get {
                return ResourceManager.GetString("FlagAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://data-live.flightradar24.com/clickhandler/?flight=.
        /// </summary>
        internal static string FlightAPI {
            get {
                return ResourceManager.GetString("FlightAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://geocode.maps.co/reverse?lat={0}&amp;lon={1}&amp;api_key=665341c45e157375825035nzcf32853.
        /// </summary>
        internal static string GeocodeCoordinatesAPI {
            get {
                return ResourceManager.GetString("GeocodeCoordinatesAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://geocode.maps.co/search?q={0}&amp;api_key=665341c45e157375825035nzcf32853.
        /// </summary>
        internal static string GeocodeCountryAPI {
            get {
                return ResourceManager.GetString("GeocodeCountryAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.openweathermap.org/data/2.5/weather?lat={0}&amp;lon={1}&amp;appid=1da046937a4768b13d3e725e2d4a1b4a&amp;units=metric.
        /// </summary>
        internal static string WeatherAPI {
            get {
                return ResourceManager.GetString("WeatherAPI", resourceCulture);
            }
        }
    }
}
